version: '3.8'

services:
  flaskcam:
    build: .
    restart: always
    privileged: true
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
